### ISSUE TITLE
How to bring up the telescope view

### ISSUE THREAD

**Issue by callmiy** [emmanueltouzery/elixir-extras.nvim#3]
Hi @emmanueltouzery 

Thanks for the plugin. May be it is obvious to others, but I have no idea how to bring up the telescope modal. Sorry I have never used telescope so may be that is my issue.

I am sure the plugin works because as soon as I open an elixir project, the telescope modal pops up and I hit `<esc>` twice to dismiss the modal. Thereafter, I have no idea how bring up the modal again except I close and reopen my project.

**Comment by emmanueltouzery** [comment]
hm. try in normal mode, to type this, from the readme:
```
:lua require('elixir-extras').elixir_view_docs({include_mix_libs=true})
```

so, `:` to enter command mode, then type the text starting with lua, and at the end press enter. does that work?

**Comment by callmiy** [comment]
Oh I see 😂. I actually put that in the `config` section of `packer.nvim` (that's why it pops up on entering the project). I will now bind it to a key. Thanks

**Comment by emmanueltouzery** [comment]
great!
